import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "src/types/database.generated.ts",
    // Generated by the Supabase CLI at `supabase start`. Not our code.
    "supabase/.temp/**",
  ]),

  {
    rules: {
      // `any` erases the type safety the generated database types exist to provide.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },

  {
    // Second line of defence around the service-role client. `admin.ts` already has
    // `import 'server-only'`, which turns a Client Component import into a build error; this rule
    // catches it at lint time with a message that says why, and covers the presentational layer
    // where such an import is never legitimate regardless of rendering mode.
    files: ["src/components/**/*.{ts,tsx}", "src/app/**/*.tsx"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/lib/supabase/admin",
              message:
                "The service-role client bypasses RLS and must stay in server-only modules. Use @/lib/supabase/server instead.",
            },
          ],
        },
      ],
    },
  },

  {
    files: ["tests/**/*.ts"],
    rules: {
      // Tests arrange state deliberately and are not part of the shipped bundle.
      "no-restricted-imports": "off",
    },
  },
]);

export default eslintConfig;
